[package]
name = "sparklet"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.2"
actix-rt = "2.9.0"
actix-web = "4.3.1"
const_format = "0.2.31"
lazy_static = "1.4.0"
libdx = "1.0.0"
