version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: always
  db:
    image: mariadb
    env_file:
      - .env
    environment:
      - MARIADB_DATABASE=sparklet_main
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3001:3306"
